import type { NoteStatus, NoteType } from '../types'

export const TYPE_LABELS: Record<NoteType, string> = {
  prospect: 'Prospect',
  account: 'Account',
  call_summary: 'Call',
  followup: 'Followup',
  objection: 'Objection',
  email_draft: 'Email draft',
  linkedin_draft: 'LinkedIn draft',
  automation_result: 'Automation',
  task: 'Task',
  general_note: 'Note',
  box: 'Box',
  daily_briefing: 'Today',
  command_center: 'Command center',
  automation_hub: 'Automation hub',
  stripe: 'Stripe',
  search: 'Search',
  ai_assistant: 'AI assistant',
  inbox: 'Inbox',
  settings: 'Settings',
  voice_note: 'Voice note',
  screenshot: 'Screenshot',
  meeting: 'Meeting',
  capture: 'Capture',
  email: 'Email',
  home_zone: 'Home Zone',
  email_zone: 'Email Zone',
  notes_zone: 'Notes Zone',
  tasks_zone: 'Tasks Zone',
  automation_zone: 'Automation Zone',
}

export const TYPE_ACCENT: Record<NoteType, string> = {
  prospect: 'border-l-blue-500',
  account: 'border-l-emerald-500',
  call_summary: 'border-l-purple-500',
  followup: 'border-l-amber-500',
  objection: 'border-l-red-500',
  email_draft: 'border-l-sky-500',
  linkedin_draft: 'border-l-indigo-500',
  automation_result: 'border-l-fuchsia-500',
  task: 'border-l-slate-500',
  general_note: 'border-l-slate-400',
  box: 'border-l-stone-400',
  daily_briefing: 'border-l-amber-400',
  command_center: 'border-l-slate-900',
  automation_hub: 'border-l-fuchsia-400',
  stripe: 'border-l-violet-500',
  search: 'border-l-cyan-500',
  ai_assistant: 'border-l-violet-500',
  inbox: 'border-l-orange-400',
  settings: 'border-l-slate-500',
  voice_note: 'border-l-pink-500',
  screenshot: 'border-l-teal-500',
  meeting: 'border-l-rose-500',
  capture: 'border-l-fuchsia-400',
  email: 'border-l-yellow-500',
  home_zone: 'border-l-amber-500',
  email_zone: 'border-l-yellow-500',
  notes_zone: 'border-l-blue-500',
  tasks_zone: 'border-l-emerald-500',
  automation_zone: 'border-l-fuchsia-500',
}

export const TYPE_BG: Record<NoteType, string> = {
  prospect: 'bg-blue-50',
  account: 'bg-emerald-50',
  call_summary: 'bg-purple-50',
  followup: 'bg-amber-50',
  objection: 'bg-red-50',
  email_draft: 'bg-sky-50',
  linkedin_draft: 'bg-indigo-50',
  automation_result: 'bg-fuchsia-50',
  task: 'bg-slate-50',
  general_note: 'bg-white',
  box: 'bg-stone-50',
  daily_briefing: 'bg-amber-50/40',
  command_center: 'bg-slate-50',
  automation_hub: 'bg-fuchsia-50',
  stripe: 'bg-violet-50',
  search: 'bg-cyan-50',
  ai_assistant: 'bg-violet-50',
  inbox: 'bg-orange-50',
  settings: 'bg-slate-50',
  voice_note: 'bg-pink-50',
  screenshot: 'bg-teal-50',
  meeting: 'bg-rose-50',
  capture: 'bg-fuchsia-50',
  email: 'bg-yellow-50',
  home_zone: 'bg-amber-50/60',
  email_zone: 'bg-yellow-50/60',
  notes_zone: 'bg-blue-50/60',
  tasks_zone: 'bg-emerald-50/60',
  automation_zone: 'bg-fuchsia-50/60',
}

export const STATUS_BADGE: Record<NoteStatus, string> = {
  open: 'bg-slate-200 text-slate-700',
  in_progress: 'bg-amber-200 text-amber-900',
  resolved: 'bg-emerald-200 text-emerald-900',
  dismissed: 'bg-slate-200 text-slate-500',
  needs_review: 'bg-red-200 text-red-900',
}

export const STATUS_LABEL: Record<NoteStatus, string> = {
  open: 'Open',
  in_progress: 'In progress',
  resolved: 'Resolved',
  dismissed: 'Dismissed',
  needs_review: 'Needs review',
}
